apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-dehazer-deployment
  labels:
    app: image-dehazer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-dehazer
  template:
    metadata:
      labels:
        app: image-dehazer
    spec:
      containers:
      - name: image-dehazer-container
        image: dehazer-app:latest  # <-- update this
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: image-dehazer-service
spec:
  selector:
    app: image-dehazer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
